//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impressao
{
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase
	{
		
		private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
		
		public static Settings1 Default
		{
			get
			{
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Sim")]
		public string DescriçãoNoPDF
		{
			get
			{
				return ((string)(this["DescriçãoNoPDF"]));
			}
			set
			{
				this["DescriçãoNoPDF"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public string EspessuraLayer
		{
			get
			{
				return ((string)(this["EspessuraLayer"]));
			}
			set
			{
				this["EspessuraLayer"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("PDF")]
		public string Impressora
		{
			get
			{
				return ((string)(this["Impressora"]));
			}
			set
			{
				this["Impressora"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Sim")]
		public string ImprimeCotas
		{
			get
			{
				return ((string)(this["ImprimeCotas"]));
			}
			set
			{
				this["ImprimeCotas"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Não")]
		public string SalvarDesenhos
		{
			get
			{
				return ((string)(this["SalvarDesenhos"]));
			}
			set
			{
				this["SalvarDesenhos"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("A0")]
		public string TamanhoFormato
		{
			get
			{
				return ((string)(this["TamanhoFormato"]));
			}
			set
			{
				this["TamanhoFormato"] = value;
			}
		}
	}
}
